FROM java:11.0.7

RUN mkdir /app

ADD /build/libs/app-*.jar /app\app/jar

EXPOSE 8080

ENTRYPOINT [ "java", "-Djava.security.egd=file:/dev/./urandom" ,"-jar", "/app/app.jar" ]

#trocar javaecs por app?
#docker run --name banco1 -d -p 8080:80 banco_db